spring:
  application:
    name: gateway-service
  
  config:
    import:
      - "optional:configserver:http://localhost:8888"
  
  cloud:
    config:
      enabled: true
      uri: http://localhost:8888
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1

