spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
      fail-fast: false
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

# Puerto del Discovery Service
server:
  port: 8761

# Configuración básica de Eureka (será sobrescrita por Config Server)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# Configuración específica del Gobierno de Tabasco
tabasco:
  gov:
    discovery:
      sistema: "Sistema de Acceso Unificado"
      version: "1.0.0"
      descripcion: "Servidor de descubrimiento para microservicios del Gobierno de Tabasco"
      responsable: "CGMAIG"
