# Configuración para Auth Service - PRODUCCIÓN
server:
  port: 8081

spring:
  application:
    name: auth-service
  
  # PostgreSQL Production
  datasource:
    url: ${DB_URL:jdbc:postgresql://prod-db-cluster:5432/acceso_tabasco}
    username: ${DB_USER:auth_prod}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: America/Mexico_City
          batch_size: 20
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}
          cache-duration: PT1H

# Eureka Client - Production
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://discovery.tabasco.gob.mx/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:auth-service.tabasco.gob.mx}
    instance-id: ${spring.application.name}:${HOSTNAME:auth-service}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      management.port: ${management.server.port:8081}
      management.context-path: ${management.endpoints.web.base-path:/actuator}

# Keycloak Production - All secrets from environment variables
keycloak:
  url: ${KEYCLOAK_URL}
  realm: ${KEYCLOAK_REALM}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  client-id: ${KEYCLOAK_CLIENT_ID}
  auth-server-url: ${KEYCLOAK_URL}
  resource: ${KEYCLOAK_CLIENT_ID}
  public-client: false
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

# Configuración específica de producción
tabasco:
  gov:
    sistema:
      nombre: "Sistema de Acceso Unificado"
      version: "1.0.0"
      descripcion: "Servicio de Autenticación para el Gobierno de Tabasco"
    dependencia:
      responsable: "CGMAIG"
      contacto: "soporte-acceso@tabasco.gob.mx"
    nomina:
      validation:
        required-status: ACTIVO
        cache-duration: PT1H # Cache más largo en producción
      view:
        name: vw_empleados_nomina
    security:
      session-timeout: 3600 # 1 hora en producción
      max-login-attempts: 3 # Más restrictivo en prod
      lockout-duration: 1800 # 30 minutos de bloqueo

# Actuator - Production (endpoints limitados)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    info:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s,2s

# Logging - Production (optimizado)
logging:
  level:
    saf.cgmaig.auth: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    org.springframework.cloud: INFO
    root: WARN
