# Concept Management Service - Configuración de Desarrollo
server:
  port: 8086

spring:
  application:
    name: concept-management-service
  
  # PostgreSQL Development - Base de datos compartida con validation-service y technical-concept-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/acceso_tabasco_dev}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:activo}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 600000
  
  jpa:
    hibernate:
      ddl-auto: update    # Crear tablas si no existen
    show-sql: false       # Menos verbose para servicio de gestión
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: America/Mexico_City

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.nucleo.rocks/realms/nucleo-dash-realm}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://auth.nucleo.rocks/realms/nucleo-dash-realm/protocol/openid-connect/certs}

# Eureka Client - Development
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: false
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Configuración específica de Concept Management Service
cubs:
  concept-management:
    # Configuración de estados de conceptos
    concept-status:
      draft: "DRAFT"
      submitted: "SUBMITTED"
      approved: "APPROVED"
      rejected: "REJECTED"
    # Configuración de validación
    validation:
      auto-validate-on-submit: true
      allow-submit-with-warnings: true
      require-comments-on-rejection: true
    # Configuración de auditoría
    audit:
      enabled: true
      track-all-changes: true
      retention-days: 365
    # Configuración de cache
    cache:
      enabled: true
      ttl-minutes: 15
      max-entries: 500

# Feign Client Configuration (para comunicarse con technical-concept-service y validation-service)
feign:
  client:
    config:
      technical-concept-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
      validation-service:
        connectTimeout: 5000
        readTimeout: 15000  # Mayor timeout para validaciones
        loggerLevel: basic

# Actuator - Development
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,concept-stats,cache-stats
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    concept-stats:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Logging - Development
logging:
  level:
    saf.cgmaig.conceptmanagement: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.cloud.config: INFO
    feign: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
