# Configuración para Technical Concept Service - PRODUCCIÓN
server:
  port: 8083

spring:
  application:
    name: technical-concept-service
  
  # PostgreSQL Production
  datasource:
    url: ${DB_URL:jdbc:postgresql://db-server:5432/acceso_tabasco_prod}
    username: ${DB_USER:technical_concept_prod}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: America/Mexico_City
        connection:
          provider_disables_autocommit: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI}

# Eureka Client - Production
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:technical-concept-service}
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

# Configuración específica de producción
cubs:
  technical-concepts:
    validation:
      enable-area-capitulo-validation: true
      enable-name-uniqueness-check: true
    audit:
      enable-change-tracking: true
      retention-days: 2555 # 7 años para auditoría gubernamental
    security:
      enable-area-based-access: true
      allow-cross-area-read: false
    performance:
      enable-caching: true
      cache-ttl: 3600 # 1 hora

# Actuator - Production (endpoints limitados)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Logging - Production (menos verbose)
logging:
  level:
    root: WARN
    saf.cgmaig.technicalconcept: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/cubs/technical-concept-service.log
    max-size: 100MB
    max-history: 30