# Configuración para User Management Service - PRODUCCIÓN
server:
  port: 8082

spring:
  application:
    name: user-management-service
  
  # PostgreSQL Production
  datasource:
    url: ${DB_URL:jdbc:postgresql://prod-db-cluster:5432/acceso_tabasco}
    username: ${DB_USER:user_mgmt_prod}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        jdbc:
          time_zone: America/Mexico_City
          batch_size: 20
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

  # Liquibase para migraciones
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: prod

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://keycloak.tabasco.gob.mx/realms/acceso-tabasco}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:https://keycloak.tabasco.gob.mx/realms/acceso-tabasco/protocol/openid-connect/certs}
          cache-duration: PT1H

# Eureka Client - Production
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:https://discovery.tabasco.gob.mx/eureka}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:user-mgmt-service.tabasco.gob.mx}
    instance-id: ${spring.application.name}:${HOSTNAME:user-mgmt-service}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      management.port: ${management.server.port:8082}
      management.context-path: ${management.endpoints.web.base-path:/actuator}

# Keycloak Production
keycloak:
  realm: acceso-tabasco
  auth-server-url: ${KEYCLOAK_URL:https://keycloak.tabasco.gob.mx}
  resource: user-management-client-prod
  public-client: false
  verify-token-audience: true
  use-resource-role-mappings: true
  confidential-port: 0
  credentials:
    secret: ${KEYCLOAK_USER_MGMT_CLIENT_SECRET}

# Configuración específica de producción
tabasco:
  gov:
    sistema:
      nombre: "Sistema de Gestión de Usuarios"
      version: "1.0.0"
      descripcion: "Servicio de Gestión de Usuarios para el Gobierno de Tabasco"
    dependencia:
      responsable: "CGMAIG"
      contacto: "soporte-usuarios@tabasco.gob.mx"
    user-management:
      default-role: "USER_BASIC"
      auto-create-profiles: false # Más control en producción
      sync-with-nomina: true
      password-policy:
        min-length: 12
        require-uppercase: true
        require-lowercase: true
        require-numbers: true
        require-special-chars: true
        history-count: 12 # Recordar últimas 12 contraseñas
        expiry-days: 90 # Cambio obligatorio cada 90 días
      session:
        timeout: 3600 # 1 hora en producción
        max-concurrent-sessions: 3 # Más restrictivo
        prevent-concurrent-logins: true
      audit:
        enabled: true
        retention-days: 365
        detailed-logging: true

# Actuator - Production (endpoints limitados)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    info:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,300ms,500ms,1s,2s

# Logging - Production (optimizado)
logging:
  level:
    saf.cgmaig.usermanagement: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.springframework.web: WARN
    org.springframework.cloud: INFO
    liquibase: INFO
    root: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{traceId},%X{spanId}] [%thread] %-5level %logger{36} - %msg%n"
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  file:
    name: /var/log/user-management-service/user-management-service.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

# Configuración de SSL para conexiones externas
server:
  ssl:
    enabled: false # Se maneja en el load balancer
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css